version: 3.7+av{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - coverity_scan

image: Visual Studio 2015

shallow_clone: true

matrix:
  fast_finish: true

environment:
  PovBuildDefs: POV_RAY_IS_AUTOBUILD=1;POV_RAY_BUILD_ID="av$(APPVEYOR_BUILD_NUMBER)";BUILT_BY="AppVeyor";
  matrix:
  - configuration: Release
    platform: x64
    bin_dir: bin64
    artifact_suffix: -Win64
    PlatformToolset: v140
  - configuration: Release-SSE2
    platform: Win32
    bin_dir: bin32
    artifact_suffix: -Win32-sse2
    PlatformToolset: v140
  - configuration: Release
    platform: Win32
    bin_dir: bin32
    artifact_suffix: -Win32
    PlatformToolset: v140

before_build:
- ps: |
    $env:devenv = $env:VS140COMNTOOLS + '\..\IDE\devenv'
    & $env:devenv windows\vs10\povray.sln /upgrade

build:
  project: windows/vs10/povray.sln
  parallel: true
  verbosity: minimal

test: off
